export default `
# AccordJS Environment Configuration
# This file is automatically generated by AccordJS CLI.

TOKEN = 'YOUR_BOT_TOKEN'
CLIENT_ID = 'YOUR_CLIENT_ID'


ACCORDJS_DEV_GUILDS = 'GUILD_FOR_DEV_1,GUILD_FOR_DEV_2' # Comma-separated list of guild IDs for development mode
`.trim();