export default `
import { initializeFromWebpack, SOURCE_CODE_FILE_REGEX } from 'accordjs';

// ~ This file is automatically generated by AccordJS. ~
// This file is temporary. It is generated by AccordJS to create the build, and is then automatically deleted.
// If the file hasn't been deleted and no build is in progress, you can delete it.

// Import the context from Webpack to dynamically load source code files
const context = require.context("./", true, SOURCE_CODE_FILE_REGEX);

// Initialize AccordJS with the context
initializeFromWebpack(context)
`.trim();